[package]
name = "browser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.5"
native-tls = "0.2.11"
notan = { version = "0.12.0", features = ["notan_text","text"] }
